# Generated by Django 3.2.7 on 2021-10-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20211002_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
