# Generated by Django 4.0 on 2021-12-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_orderitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
