# Generated by Django 4.0 on 2021-12-08 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totals',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.user'),
        ),
    ]
