# Generated by Django 4.0 on 2021-12-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_order_totals_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='times',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
